version: "3.8"

services:
   mongo-db-nestor:
      image: mongo:6.0.6
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: mongouser
         MONGO_INITDB_ROOT_PASSWORD: mongo
       ##  MONGO_INITDB_DATABASE: mongo
       ## MONGO_USERNAME: admin
       ##  MONGO_PASSWORD: secret
       ##  DB_NAME: dbnestor

      volumes:
         - ./mongo:/data/db
     ##    - .mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      ports:
         - 27017:27017
